parameters:
    lyssal.seo.administrator.host.class: 'Lyssal\SeoBundle\Doctrine\Administrator\HostAdministrator'
    lyssal.seo.administrator.page.class: 'Lyssal\SeoBundle\Doctrine\Administrator\PageAdministrator'
    lyssal.seo.administrator.website.class: 'Lyssal\SeoBundle\Doctrine\Administrator\WebsiteAdministrator'

services:
    _defaults:
        public: true

    lyssal.seo.administrator.host:
        class: '%lyssal.seo.administrator.host.class%'
        arguments: ['@doctrine.orm.entity_manager', '%lyssal.seo.entity.host.class%']

    lyssal.seo.administrator.page:
        class: '%lyssal.seo.administrator.page.class%'
        arguments: ['@doctrine.orm.entity_manager', '%lyssal.seo.entity.page.class%']

    lyssal.seo.administrator.website:
        class: '%lyssal.seo.administrator.website.class%'
        arguments: ['@doctrine.orm.entity_manager', '%lyssal.seo.entity.website.class%']
