parameters:
    lyssal.seo.event_listener.page_entity_setter.class: 'Lyssal\SeoBundle\EventListener\PageEntitySetter'
    lyssal.seo.event_listener.page_slugger.class: 'Lyssal\SeoBundle\EventListener\PageSlugger'

services:
    _defaults:
        autowire: true

    lyssal.seo.event_listener.page_entity_setter:
        class: '%lyssal.seo.event_listener.page_entity_setter.class%'
        public: false
        tags:
            - { name: 'doctrine.event_listener', event: 'postPersist' }
            - { name: 'doctrine.event_listener', event: 'postUpdate' }

    lyssal.seo.event_listener.page_slugger:
        class: '%lyssal.seo.event_listener.page_slugger.class%'
        public: false
        tags:
            - { name: 'doctrine.event_listener', event: 'postPersist' }
            - { name: 'doctrine.event_listener', event: 'postUpdate' }
