parameters:
    lyssal.seo.manager.host.class: 'Lyssal\SeoBundle\Manager\HostManager'
    lyssal.seo.manager.page.class: 'Lyssal\SeoBundle\Manager\PageManager'
    lyssal.seo.manager.website.class: 'Lyssal\SeoBundle\Manager\WebsiteManager'

services:
    _defaults:
        public: true

    lyssal.seo.manager.host:
        class: '%lyssal.seo.manager.host.class%'
        arguments: ['@doctrine.orm.entity_manager', '%lyssal.seo.entity.host.class%']

    lyssal.seo.manager.page:
        class: '%lyssal.seo.manager.page.class%'
        arguments: ['@doctrine.orm.entity_manager', '%lyssal.seo.entity.page.class%']

    lyssal.seo.manager.website:
        class: '%lyssal.seo.manager.website.class%'
        arguments: ['@doctrine.orm.entity_manager', '%lyssal.seo.entity.website.class%']
