easy_admin:
    entities:
        Page:
            class: '%lyssal.seo.entity.page.class%'
            label: 'page'
            translation_domain: 'LyssalSeoBundle'
            list:
                fields:
                    - { property: 'website', label: 'website' }
                    - { property: 'title', label: 'title' }
                    - { property: 'online', label: 'online' }
            form:
                fields:
                    - { property: 'website', label: 'website', type_options: { translation_domain: 'LyssalSeoBundle' } }
                    - { property: 'online', label: 'online', type_options: { translation_domain: 'LyssalSeoBundle' } }
                    - { property: 'title', label: 'title', type_options: { translation_domain: 'LyssalSeoBundle' } }
                    - { property: 'slug', label: 'slug', type_options: { translation_domain: 'LyssalSeoBundle' } }
                    - { property: 'description', label: 'description', type_options: { translation_domain: 'LyssalSeoBundle' } }
                    - { property: 'locale', label: 'locale', type_options: { translation_domain: 'LyssalSeoBundle' } }
                    - { property: 'indexed', label: 'indexed', type_options: { translation_domain: 'LyssalSeoBundle' } }
                    - { property: 'followed', label: 'followed', type_options: { translation_domain: 'LyssalSeoBundle' } }
                    -
                        property: 'modificationFrequency'
                        label: 'modification_frequency'
                        type: 'choice'
                        type_options:
                            choices:
                                frequency.always: 'always'
                                frequency.hourly: 'hourly'
                                frequency.daily: 'daily'
                                frequency.weekly: 'weekly'
                                frequency.monthly: 'monthly'
                                frequency.yearly: 'yearly'
                                frequency.never: 'never'
                            translation_domain: 'LyssalSeoBundle'
                    - { property: 'priority', label: 'priority', type_options: { translation_domain: 'LyssalSeoBundle' } }
                    - { property: 'category', label: 'category', type_options: { translation_domain: 'LyssalSeoBundle' } }
                    - { property: 'author', label: 'author', type_options: { translation_domain: 'LyssalSeoBundle' } }
                    - { property: 'independent', label: 'page.independent', type_options: { translation_domain: 'LyssalSeoBundle' } }
                    - { property: 'content', label: 'content', type_options: { translation_domain: 'LyssalSeoBundle' } }
