easy_admin:
    entities:
        Page:
            class: '%lyssal.seo.entity.page.class%'
            form:
                fields:
                    - 'website'
                    - 'online'
                    - 'title'
                    - 'slug'
                    - 'description'
                    - 'locale'
                    - 'indexed'
                    - 'followed'
                    - 'modificationFrequency'
                    - 'priority'
                    - 'category'
                    - 'author'
                    - 'independent'
                    - 'content'
