easy_admin:
    entities:
        Website:
            class: '%lyssal.seo.entity.website.class%'
            form:
                fields:
                    - 'title'
                    - 'domain'
                    - 'author'
                    - 'publisher'
                    - 'copyright'
                    - 'generator'
                    - 'replyTo'
