easy_admin:
    entities:
        Website:
            class: '%lyssal.seo.entity.website.class%'
            label: 'website'
            translation_domain: 'LyssalSeoBundle'
            list:
                fields:
                    - { property: 'title', label: 'title' }
            form:
                fields:
                    - { property: 'title', label: 'title', type_options: { translation_domain: 'LyssalSeoBundle' } }
                    - { property: 'homePage', label: 'home_page', type_options: { translation_domain: 'LyssalSeoBundle' } }
                    - { property: 'byDefault', label: 'by_default', type_options: { translation_domain: 'LyssalSeoBundle' } }
                    - { property: 'hosts', label: 'hosts', type: 'collection', type_options: { entry_type: 'Lyssal\SeoBundle\Form\Type\HostType', by_reference: false, translation_domain: 'LyssalSeoBundle' } }
                    - { property: 'author', label: 'author', type_options: { translation_domain: 'LyssalSeoBundle' } }
                    - { property: 'publisher', label: 'publisher', type_options: { translation_domain: 'LyssalSeoBundle' } }
                    - { property: 'copyright', label: 'copyright', type_options: { translation_domain: 'LyssalSeoBundle' } }
                    - { property: 'generator', label: 'generator', type_options: { translation_domain: 'LyssalSeoBundle' } }
                    - { property: 'replyTo', label: 'reply_to', type_options: { translation_domain: 'LyssalSeoBundle' } }
