easy_admin:
    entities:
        Website:
            class: '%lyssal.seo.entity.website.class%'
            form:
                fields:
                    - 'title'
                    - 'homePage'
                    - 'byDefault'
                    - { property: 'hosts', type: 'collection', type_options: { entry_type: 'Lyssal\SeoBundle\Form\Type\HostType', by_reference: false } }
                    - 'author'
                    - 'publisher'
                    - 'copyright'
                    - 'generator'
                    - 'replyTo'
